// src/components/auth/LoginDialog.tsx
// NOTE: This file is stable and usually should not be modified.
// It is important that all functionality in this file is preserved, and should only be modified if explicitly requested.

import React, { useRef, useState, useEffect } from 'react';
import { Shield, Upload, AlertTriangle, UserPlus, KeyRound, Sparkles, Cloud } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useLoginActions } from '@/hooks/useLoginActions';
import { cn } from '@/lib/utils';

interface LoginDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onLogin: () => void;
  onSignup?: () => void;
}

const validateNsec = (nsec: string) => {
  return /^nsec1[a-zA-Z0-9]{58}$/.test(nsec);
};

const validateBunkerUri = (uri: string) => {
  return uri.startsWith('bunker://');
};

/**
 * Dialog component for user authentication with multiple login methods.
 * Supports NIP-07 browser extensions, nsec private keys, and bunker URIs.
 *
 * @param props - Component properties
 * @param props.isOpen - Whether the dialog is open
 * @param props.onClose - Callback when dialog closes
 * @param props.onLogin - Callback after successful login
 * @param props.onSignup - Optional callback for signup navigation
 */
const LoginDialog: React.FC<LoginDialogProps> = ({ isOpen, onClose, onLogin, onSignup }) => {
  const [isLoading, setIsLoading] = useState(false);
  const [isFileLoading, setIsFileLoading] = useState(false);
  const [nsec, setNsec] = useState('');
  const [bunkerUri, setBunkerUri] = useState('');
  const [errors, setErrors] = useState<{
    nsec?: string;
    bunker?: string;
    file?: string;
    extension?: string;
  }>({});
  const fileInputRef = useRef<HTMLInputElement>(null);
  const login = useLoginActions();

  // Reset all state when dialog opens/closes
  useEffect(() => {
    if (isOpen) {
      // Reset state when dialog opens
      setIsLoading(false);
      setIsFileLoading(false);
      setNsec('');
      setBunkerUri('');
      setErrors({});
      // Reset file input
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  }, [isOpen]);

  const handleExtensionLogin = async () => {
    setIsLoading(true);
    setErrors(prev => ({ ...prev, extension: undefined }));

    try {
      if (!('nostr' in window)) {
        throw new Error('Nostr extension not found. Please install a NIP-07 extension.');
      }
      await login.extension();
      onLogin();
      onClose();
    } catch (e: unknown) {
      const error = e as Error;
      console.error('Bunker login failed:', error);
      console.error('Nsec login failed:', error);
      console.error('Extension login failed:', error);
      setErrors(prev => ({
        ...prev,
        extension: error instanceof Error ? error.message : 'Extension login failed'
      }));
    } finally {
      setIsLoading(false);
    }
  };

  const executeLogin = (key: string) => {
    setIsLoading(true);
    setErrors({});

    // Use a timeout to allow the UI to update before the synchronous login call
    setTimeout(() => {
      try {
        login.nsec(key);
        onLogin();
        onClose();
      } catch {
        setErrors({ nsec: "Failed to login with this key. Please check that it's correct." });
        setIsLoading(false);
      }
    }, 50);
  };

  const handleKeyLogin = () => {
    if (!nsec.trim()) {
      setErrors(prev => ({ ...prev, nsec: 'Please enter your secret key' }));
      return;
    }

    if (!validateNsec(nsec)) {
      setErrors(prev => ({ ...prev, nsec: 'Invalid secret key format. Must be a valid nsec starting with nsec1.' }));
      return;
    }
    executeLogin(nsec);
  };

  const handleBunkerLogin = async () => {
    if (!bunkerUri.trim()) {
      setErrors(prev => ({ ...prev, bunker: 'Please enter a bunker URI' }));
      return;
    }

    if (!validateBunkerUri(bunkerUri)) {
      setErrors(prev => ({ ...prev, bunker: 'Invalid bunker URI format. Must start with bunker://' }));
      return;
    }

    setIsLoading(true);
    setErrors(prev => ({ ...prev, bunker: undefined }));

    try {
      await login.bunker(bunkerUri);
      onLogin();
      onClose();
      // Clear the URI from memory
      setBunkerUri('');
    } catch {
      setErrors(prev => ({
        ...prev,
        bunker: 'Failed to connect to bunker. Please check the URI.'
      }));
    } finally {
      setIsLoading(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsFileLoading(true);
    setErrors({});

    const reader = new FileReader();
    reader.onload = (event) => {
      setIsFileLoading(false);
      const content = event.target?.result as string;
      if (content) {
        const trimmedContent = content.trim();
        if (validateNsec(trimmedContent)) {
          executeLogin(trimmedContent);
        } else {
          setErrors({ file: 'File does not contain a valid secret key.' });
        }
      } else {
        setErrors({ file: 'Could not read file content.' });
      }
    };
    reader.onerror = () => {
      setIsFileLoading(false);
      setErrors({ file: 'Failed to read file.' });
    };
    reader.readAsText(file);
  };

  const handleSignupClick = () => {
    onClose();
    if (onSignup) {
      onSignup();
    }
  };

  const defaultTab = 'nostr' in window ? 'extension' : 'key';

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent
        className={cn("max-w-[95vw] sm:max-w-md max-h-[90vh] max-h-[90dvh] p-0 overflow-hidden rounded-2xl overflow-y-scroll")}
      >
        <DialogHeader className={cn('px-6 pt-6 pb-1 relative')}>

            <DialogDescription className="text-center">
              Sign up or log in to continue
            </DialogDescription>
        </DialogHeader>
        <div className='px-6 pt-2 pb-4 space-y-4 overflow-y-auto flex-1'>
          {/* Prominent Sign Up Section */}
          <div className='relative p-4 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-blue-950/50 dark:to-indigo-950/50 border border-blue-200 dark:border-blue-800 overflow-hidden'>
            <div className='relative z-10 text-center space-y-3'>
              <div className='flex justify-center items-center gap-2 mb-2'>
                <Sparkles className='w-5 h-5 text-blue-600' />
                <span className='font-semibold text-blue-800 dark:text-blue-200'>
                  New to Nostr?
                </span>
              </div>
              <p className='text-sm text-blue-700 dark:text-blue-300'>
                Create a new account to get started. It's free and open.
              </p>
              <Button
                onClick={handleSignupClick}
                className='w-full rounded-full py-3 text-base font-semibold bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 transform transition-all duration-200 hover:scale-105 shadow-lg border-0'
              >
                <UserPlus className='w-4 h-4 mr-2' />
                <span>Sign Up</span>
              </Button>
            </div>
          </div>

          {/* Divider */}
          <div className='relative'>
            <div className='absolute inset-0 flex items-center'>
              <div className='w-full border-t border-gray-300 dark:border-gray-600'></div>
            </div>
            <div className='relative flex justify-center text-sm'>
              <span className='px-3 bg-background text-muted-foreground'>
                <span>Or log in</span>
              </span>
            </div>
          </div>

          {/* Login Methods */}
          <Tabs defaultValue={defaultTab} className="w-full">
            <TabsList className="grid w-full grid-cols-3 bg-muted/80 rounded-lg mb-4">
              <TabsTrigger value="extension" className="flex items-center gap-2">
                <Shield className="w-4 h-4" />
                <span>Extension</span>
              </TabsTrigger>
              <TabsTrigger value="key" className="flex items-center gap-2">
                <KeyRound className="w-4 h-4" />
                <span>Key</span>
              </TabsTrigger>
              <TabsTrigger value="bunker" className="flex items-center gap-2">
                <Cloud className="w-4 h-4" />
                <span>Bunker</span>
              </TabsTrigger>
            </TabsList>
            <TabsContent value='extension' className='space-y-3 bg-muted'>
              {errors.extension && (
                <Alert variant="destructive">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>{errors.extension}</AlertDescription>
                </Alert>
              )}
              <div className='text-center p-4 rounded-lg bg-gray-50 dark:bg-gray-800'>
                <Shield className='w-12 h-12 mx-auto mb-3 text-primary' />
                <p className='text-sm text-gray-600 dark:text-gray-300 mb-4'>
                  Login with one click using the browser extension
                </p>
                <div className="flex justify-center">
                  <Button
                    className='w-full rounded-full py-4'
                    onClick={handleExtensionLogin}
                    disabled={isLoading}
                  >
                    {isLoading ? 'Logging in...' : 'Login with Extension'}
                  </Button>
                </div>
              </div>
            </TabsContent>

            <TabsContent value='key' className='space-y-4'>
              <div className='space-y-4'>
                <div className='space-y-2'>
                  <label htmlFor='nsec' className='text-sm font-medium'>
                    Secret Key (nsec)
                  </label>
                  <Input
                    id='nsec'
                    type="password"
                    value={nsec}
                    onChange={(e) => {
                      setNsec(e.target.value);
                      if (errors.nsec) setErrors(prev => ({ ...prev, nsec: undefined }));
                    }}
                    className={`rounded-lg ${
                      errors.nsec ? 'border-red-500 focus-visible:ring-red-500' : ''
                    }`}
                    placeholder='nsec1...'
                    autoComplete="off"
                  />
                  {errors.nsec && (
                    <p className="text-sm text-red-500">{errors.nsec}</p>
                  )}
                </div>

                <Button
                  className='w-full rounded-full py-3'
                  onClick={handleKeyLogin}
                  disabled={isLoading || !nsec.trim()}
                >
                  {isLoading ? 'Verifying...' : 'Log In'}
                </Button>

                <div className='relative'>
                  <div className='absolute inset-0 flex items-center'>
                    <div className='w-full border-t border-muted'></div>
                  </div>
                  <div className='relative flex justify-center text-xs'>
                    <span className='px-2 bg-background text-muted-foreground'>
                      or
                    </span>
                  </div>
                </div>

                <div className='text-center'>
                  <input
                    type='file'
                    accept='.txt'
                    className='hidden'
                    ref={fileInputRef}
                    onChange={handleFileUpload}
                  />
                  <Button
                    variant='outline'
                    className='w-full'
                    onClick={() => fileInputRef.current?.click()}
                    disabled={isLoading || isFileLoading}
                  >
                    <Upload className='w-4 h-4 mr-2' />
                    {isFileLoading ? 'Reading File...' : 'Upload Your Key File'}
                  </Button>
                  {errors.file && (
                    <p className="text-sm text-red-500 mt-2">{errors.file}</p>
                  )}
                </div>
              </div>
            </TabsContent>

            <TabsContent value='bunker' className='space-y-3 bg-muted'>
              <div className='space-y-2'>
                <label htmlFor='bunkerUri' className='text-sm font-medium text-gray-700 dark:text-gray-400'>
                  Bunker URI
                </label>
                <Input
                  id='bunkerUri'
                  value={bunkerUri}
                  onChange={(e) => {
                    setBunkerUri(e.target.value);
                    if (errors.bunker) setErrors(prev => ({ ...prev, bunker: undefined }));
                  }}
                  className={`rounded-lg border-gray-300 dark:border-gray-700 focus-visible:ring-primary ${
                    errors.bunker ? 'border-red-500' : ''
                  }`}
                  placeholder='bunker://'
                  autoComplete="off"
                />
                {errors.bunker && (
                  <p className="text-sm text-red-500">{errors.bunker}</p>
                )}
              </div>

              <div className="flex justify-center">
                <Button
                  className='w-full rounded-full py-4'
                  onClick={handleBunkerLogin}
                  disabled={isLoading || !bunkerUri.trim()}
                >
                  {isLoading ? 'Connecting...' : 'Login with Bunker'}
                </Button>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </DialogContent>
    </Dialog>
    );
  };

export default LoginDialog;

// src/lib/components/auth/LoginDialog.svelte
<script lang="ts">
  // NOTE: This file is stable and usually should not be modified.
  // It is important that all functionality in this file is preserved, and should only be modified if explicitly requested.

  import { cn } from '$lib/utils';
  import { browser } from '$app/environment';
  import {
    loginWithExtension,
    loginWithNsec,
    loginWithBunker,
    hasNostrExtension,
    validateNsec,
    validateBunkerUri
  } from '$lib/stores/auth';

  interface Props {
    isOpen: boolean;
    onClose: () => void;
    onLogin: () => void;
    onSignup?: () => void;
  }

  let { isOpen = $bindable(), onClose, onLogin, onSignup }: Props = $props();

  let isLoading = $state(false);
  let isFileLoading = $state(false);
  let nsec = $state('');
  let bunkerUri = $state('');
  let errors = $state<{
    nsec?: string;
    bunker?: string;
    file?: string;
    extension?: string;
  }>({});
  let fileInputRef: HTMLInputElement;
  let currentTab = $state<'extension' | 'key' | 'bunker'>('extension');

  // Reset state when dialog opens/closes
  $effect(() => {
    if (isOpen) {
      isLoading = false;
      isFileLoading = false;
      nsec = '';
      bunkerUri = '';
      errors = {};
      if (fileInputRef) {
        fileInputRef.value = '';
      }
      // Set default tab based on extension availability
      if (browser && hasNostrExtension()) {
        currentTab = 'extension';
      } else {
        currentTab = 'key';
      }
    }
  });

  async function handleExtensionLogin() {
    isLoading = true;
    errors = { ...errors, extension: undefined };

    try {
      await loginWithExtension();
      onLogin();
      onClose();
    } catch (e: unknown) {
      const error = e as Error;
      console.error('Extension login failed:', error);
      errors = {
        ...errors,
        extension: error instanceof Error ? error.message : 'Extension login failed'
      };
    } finally {
      isLoading = false;
    }
  }

  function executeLogin(key: string) {
    isLoading = true;
    errors = {};

    // Use a timeout to allow the UI to update before the synchronous login call
    setTimeout(() => {
      try {
        loginWithNsec(key);
        onLogin();
        onClose();
      } catch (e: unknown) {
        const error = e as Error;
        errors = { nsec: error instanceof Error ? error.message : "Failed to login with this key. Please check that it's correct." };
        isLoading = false;
      }
    }, 50);
  }

  function handleKeyLogin() {
    if (!nsec.trim()) {
      errors = { ...errors, nsec: 'Please enter your secret key' };
      return;
    }

    if (!validateNsec(nsec)) {
      errors = { ...errors, nsec: 'Invalid secret key format. Must be a valid nsec starting with nsec1.' };
      return;
    }
    executeLogin(nsec);
  }

  async function handleBunkerLogin() {
    if (!bunkerUri.trim()) {
      errors = { ...errors, bunker: 'Please enter a bunker URI' };
      return;
    }

    if (!validateBunkerUri(bunkerUri)) {
      errors = { ...errors, bunker: 'Invalid bunker URI format. Must start with bunker://' };
      return;
    }

    isLoading = true;
    errors = { ...errors, bunker: undefined };

    try {
      await loginWithBunker(bunkerUri);
      onLogin();
      onClose();
      bunkerUri = '';
    } catch (e: unknown) {
      const error = e as Error;
      errors = {
        ...errors,
        bunker: error instanceof Error ? error.message : 'Failed to connect to bunker. Please check the URI.'
      };
    } finally {
      isLoading = false;
    }
  }

  function handleFileUpload(e: Event) {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file) return;

    isFileLoading = true;
    errors = {};

    const reader = new FileReader();
    reader.onload = (event) => {
      isFileLoading = false;
      const content = event.target?.result as string;
      if (content) {
        const trimmedContent = content.trim();
        if (validateNsec(trimmedContent)) {
          executeLogin(trimmedContent);
        } else {
          errors = { file: 'File does not contain a valid secret key.' };
        }
      } else {
        errors = { file: 'Could not read file content.' };
      }
    };
    reader.onerror = () => {
      isFileLoading = false;
      errors = { file: 'Failed to read file.' };
    };
    reader.readAsText(file);
  }

  function handleSignupClick() {
    onClose();
    if (onSignup) {
      onSignup();
    }
  }
</script>

{#if isOpen}
  <!-- Dialog Overlay -->
  <div
    class="fixed inset-0 z-50 bg-black/50"
    onclick={onClose}
    role="presentation"
  >
    <!-- Dialog Content -->
    <div
      class={cn("fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 max-w-[95vw] sm:max-w-md max-h-[90vh] max-h-[90dvh] p-0 overflow-hidden rounded-2xl overflow-y-scroll bg-background shadow-lg")}
      onclick={(e) => e.stopPropagation()}
      role="dialog"
    >
      <!-- Header -->
      <div class="px-6 pt-6 pb-1 relative">
        <p class="text-center text-muted-foreground text-sm">
          Sign up or log in to continue
        </p>
      </div>

      <!-- Content -->
      <div class="px-6 pt-2 pb-4 space-y-4 overflow-y-auto flex-1">
        <!-- Prominent Sign Up Section -->
        <div class="relative p-4 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-blue-950/50 dark:to-indigo-950/50 border border-blue-200 dark:border-blue-800 overflow-hidden">
          <div class="relative z-10 text-center space-y-3">
            <div class="flex justify-center items-center gap-2 mb-2">
              <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
              </svg>
              <span class="font-semibold text-blue-800 dark:text-blue-200">
                New to Nostr?
              </span>
            </div>
            <p class="text-sm text-blue-700 dark:text-blue-300">
              Create a new account to get started. It's free and open.
            </p>
            <button
              type="button"
              onclick={handleSignupClick}
              class="w-full rounded-full py-3 text-base font-semibold bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 transform transition-all duration-200 hover:scale-105 shadow-lg border-0 text-white"
            >
              <svg class="w-4 h-4 inline-block mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
              </svg>
              <span>Sign Up</span>
            </button>
          </div>
        </div>

        <!-- Divider -->
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-border"></div>
          </div>
          <div class="relative flex justify-center text-sm">
            <span class="px-3 bg-background text-muted-foreground">Or log in</span>
          </div>
        </div>

        <!-- Login Tabs -->
        <div class="w-full">
          <!-- Tab List -->
          <div class="grid w-full grid-cols-3 bg-muted/80 rounded-lg mb-4 p-1">
            <button
              type="button"
              onclick={() => (currentTab = 'extension')}
              class="flex items-center justify-center gap-2 px-3 py-2 rounded-md text-sm transition-colors {currentTab === 'extension' ? 'bg-background shadow-sm' : 'hover:bg-background/50'}"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              <span>Extension</span>
            </button>
            <button
              type="button"
              onclick={() => (currentTab = 'key')}
              class="flex items-center justify-center gap-2 px-3 py-2 rounded-md text-sm transition-colors {currentTab === 'key' ? 'bg-background shadow-sm' : 'hover:bg-background/50'}"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
              </svg>
              <span>Key</span>
            </button>
            <button
              type="button"
              onclick={() => (currentTab = 'bunker')}
              class="flex items-center justify-center gap-2 px-3 py-2 rounded-md text-sm transition-colors {currentTab === 'bunker' ? 'bg-background shadow-sm' : 'hover:bg-background/50'}"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
              </svg>
              <span>Bunker</span>
            </button>
          </div>

          <!-- Tab Content: Extension -->
          {#if currentTab === 'extension'}
            <div class="space-y-3">
              {#if errors.extension}
                <div class="p-3 rounded-md bg-destructive/10 text-destructive text-sm flex items-start gap-2">
                  <svg class="w-4 h-4 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                  <span>{errors.extension}</span>
                </div>
              {/if}
              <div class="text-center p-4 rounded-lg bg-muted">
                <svg class="w-12 h-12 mx-auto mb-3 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
                <p class="text-sm text-muted-foreground mb-4">
                  Login with one click using the browser extension
                </p>
                <button
                  type="button"
                  class="w-full rounded-full py-4 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
                  onclick={handleExtensionLogin}
                  disabled={isLoading}
                >
                  {isLoading ? 'Logging in...' : 'Login with Extension'}
                </button>
              </div>
            </div>
          {/if}

          <!-- Tab Content: Key -->
          {#if currentTab === 'key'}
            <div class="space-y-4">
              <div class="space-y-2">
                <label for="nsec" class="text-sm font-medium">
                  Secret Key (nsec)
                </label>
                <input
                  id="nsec"
                  type="password"
                  bind:value={nsec}
                  oninput={() => { if (errors.nsec) errors = { ...errors, nsec: undefined }; }}
                  class="w-full px-3 py-2 border rounded-lg bg-background {errors.nsec ? 'border-destructive' : ''}"
                  placeholder="nsec1..."
                  autocomplete="off"
                />
                {#if errors.nsec}
                  <p class="text-sm text-destructive">{errors.nsec}</p>
                {/if}
              </div>

              <button
                type="button"
                class="w-full rounded-full py-3 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
                onclick={handleKeyLogin}
                disabled={isLoading || !nsec.trim()}
              >
                {isLoading ? 'Verifying...' : 'Log In'}
              </button>

              <div class="relative">
                <div class="absolute inset-0 flex items-center">
                  <div class="w-full border-t border-border"></div>
                </div>
                <div class="relative flex justify-center text-xs">
                  <span class="px-2 bg-background text-muted-foreground">or</span>
                </div>
              </div>

              <div class="text-center">
                <input
                  type="file"
                  accept=".txt"
                  class="hidden"
                  bind:this={fileInputRef}
                  onchange={handleFileUpload}
                />
                <button
                  type="button"
                  class="w-full px-4 py-2 border rounded-md hover:bg-accent disabled:opacity-50"
                  onclick={() => fileInputRef?.click()}
                  disabled={isLoading || isFileLoading}
                >
                  <svg class="w-4 h-4 inline-block mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                  </svg>
                  {isFileLoading ? 'Reading File...' : 'Upload Your Key File'}
                </button>
                {#if errors.file}
                  <p class="text-sm text-destructive mt-2">{errors.file}</p>
                {/if}
              </div>
            </div>
          {/if}

          <!-- Tab Content: Bunker -->
          {#if currentTab === 'bunker'}
            <div class="space-y-3">
              <div class="space-y-2">
                <label for="bunkerUri" class="text-sm font-medium">
                  Bunker URI
                </label>
                <input
                  id="bunkerUri"
                  type="text"
                  bind:value={bunkerUri}
                  oninput={() => { if (errors.bunker) errors = { ...errors, bunker: undefined }; }}
                  class="w-full px-3 py-2 border rounded-lg bg-background {errors.bunker ? 'border-destructive' : ''}"
                  placeholder="bunker://"
                  autocomplete="off"
                />
                {#if errors.bunker}
                  <p class="text-sm text-destructive">{errors.bunker}</p>
                {/if}
              </div>

              <button
                type="button"
                class="w-full rounded-full py-4 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
                onclick={handleBunkerLogin}
                disabled={isLoading || !bunkerUri.trim()}
              >
                {isLoading ? 'Connecting...' : 'Login with Bunker'}
              </button>
            </div>
          {/if}
        </div>
      </div>
    </div>
  </div>
{/if}
