// src/lib/components/EditProfileForm.svelte
<script lang="ts">
  import { createQuery, useQueryClient } from '@tanstack/svelte-query';
  import { z } from 'zod';

  // Welshman imports for Nostr functionality
  // TODO: These imports will need to be updated once Welshman integration is complete
  // import { publishEvent } from '@welshman/...';
  // import { getCurrentUser } from '@welshman/...';

  const queryClient = useQueryClient();

  // Nostr metadata schema (from NIP-01)
  const metadataSchema = z.object({
    name: z.string().optional(),
    about: z.string().optional(),
    picture: z.string().url().optional().or(z.literal('')),
    banner: z.string().url().optional().or(z.literal('')),
    website: z.string().url().optional().or(z.literal('')),
    nip05: z.string().optional(),
    bot: z.boolean().optional(),
  });

  type NostrMetadata = z.infer<typeof metadataSchema>;

  // Form state
  let formData = $state<NostrMetadata>({
    name: '',
    about: '',
    picture: '',
    banner: '',
    website: '',
    nip05: '',
    bot: false,
  });

  let isPending = $state(false);
  let isUploading = $state(false);
  let errors = $state<Partial<Record<keyof NostrMetadata, string>>>({});

  // File input refs
  let pictureInputRef: HTMLInputElement;
  let bannerInputRef: HTMLInputElement;

  // TODO: Query current user metadata using Welshman
  // const userQuery = createQuery({
  //   queryKey: ['currentUser'],
  //   queryFn: async () => {
  //     // Fetch using Welshman
  //     return null;
  //   }
  // });

  // TODO: Load user metadata into form when available
  // $effect(() => {
  //   if ($userQuery.data?.metadata) {
  //     formData = {
  //       name: $userQuery.data.metadata.name || '',
  //       about: $userQuery.data.metadata.about || '',
  //       picture: $userQuery.data.metadata.picture || '',
  //       banner: $userQuery.data.metadata.banner || '',
  //       website: $userQuery.data.metadata.website || '',
  //       nip05: $userQuery.data.metadata.nip05 || '',
  //       bot: $userQuery.data.metadata.bot || false,
  //     };
  //   }
  // });

  // File upload handler
  async function uploadFile(file: File, field: 'picture' | 'banner') {
    isUploading = true;
    try {
      // TODO: Implement Blossom upload
      // const url = await blossomUpload(file);
      // formData[field] = url;

      console.log(`Upload ${field}:`, file.name);
      // Mock success
      alert(`${field === 'picture' ? 'Profile picture' : 'Banner'} upload not yet implemented`);
    } catch (error) {
      console.error(`Failed to upload ${field}:`, error);
      alert(`Failed to upload ${field === 'picture' ? 'profile picture' : 'banner'}`);
    } finally {
      isUploading = false;
    }
  }

  // Form submission handler
  async function handleSubmit(event: Event) {
    event.preventDefault();

    // Validate form
    const result = metadataSchema.safeParse(formData);
    if (!result.success) {
      errors = result.error.flatten().fieldErrors as any;
      return;
    }

    errors = {};
    isPending = true;

    try {
      // Clean up empty values
      const cleanData: any = {};
      for (const [key, value] of Object.entries(formData)) {
        if (value !== '' && value !== undefined) {
          cleanData[key] = value;
        }
      }

      // TODO: Publish metadata event (kind 0) using Welshman
      // await publishEvent({
      //   kind: 0,
      //   content: JSON.stringify(cleanData),
      //   tags: [],
      // });

      console.log('Publishing metadata:', cleanData);

      // TODO: Invalidate queries to refresh data
      // await queryClient.invalidateQueries({ queryKey: ['currentUser'] });

      alert('Profile updated successfully! (Note: actual publishing not yet implemented)');
    } catch (error) {
      console.error('Failed to update profile:', error);
      alert('Failed to update profile. Please try again.');
    } finally {
      isPending = false;
    }
  }

  function handleFileSelect(event: Event, field: 'picture' | 'banner') {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (file) {
      uploadFile(file, field);
    }
  }
</script>

<div class="max-w-2xl mx-auto p-6">
  <h2 class="text-2xl font-bold mb-6">Edit Profile</h2>

  <form onsubmit={handleSubmit} class="space-y-6">
    <!-- Name -->
    <div class="space-y-2">
      <label for="name" class="block text-sm font-medium">
        Name
      </label>
      <input
        id="name"
        type="text"
        bind:value={formData.name}
        placeholder="Your name"
        class="w-full px-3 py-2 border rounded-md bg-background"
      />
      <p class="text-sm text-muted-foreground">
        This is your display name that will be displayed to others.
      </p>
      {#if errors.name}
        <p class="text-sm text-destructive">{errors.name}</p>
      {/if}
    </div>

    <!-- About -->
    <div class="space-y-2">
      <label for="about" class="block text-sm font-medium">
        Bio
      </label>
      <textarea
        id="about"
        bind:value={formData.about}
        placeholder="Tell others about yourself"
        rows="4"
        class="w-full px-3 py-2 border rounded-md bg-background resize-none"
      ></textarea>
      <p class="text-sm text-muted-foreground">
        A short description about yourself.
      </p>
      {#if errors.about}
        <p class="text-sm text-destructive">{errors.about}</p>
      {/if}
    </div>

    <!-- Picture and Banner -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <!-- Picture -->
      <div class="space-y-2">
        <label for="picture" class="block text-sm font-medium">
          Profile Picture
        </label>
        <input
          id="picture"
          type="text"
          bind:value={formData.picture}
          placeholder="https://example.com/profile.jpg"
          class="w-full px-3 py-2 border rounded-md bg-background"
        />
        <div class="flex items-center gap-2">
          <input
            bind:this={pictureInputRef}
            type="file"
            accept="image/*"
            onchange={(e) => handleFileSelect(e, 'picture')}
            class="hidden"
          />
          <button
            type="button"
            onclick={() => pictureInputRef?.click()}
            class="px-3 py-1.5 text-sm border rounded-md hover:bg-accent"
          >
            Upload Image
          </button>
          {#if formData.picture}
            <div class="h-10 w-10 rounded overflow-hidden">
              <img
                src={formData.picture}
                alt="Profile preview"
                class="h-full w-full object-cover"
              />
            </div>
          {/if}
        </div>
        <p class="text-sm text-muted-foreground">
          URL to your profile picture. You can upload an image or provide a URL.
        </p>
      </div>

      <!-- Banner -->
      <div class="space-y-2">
        <label for="banner" class="block text-sm font-medium">
          Banner Image
        </label>
        <input
          id="banner"
          type="text"
          bind:value={formData.banner}
          placeholder="https://example.com/banner.jpg"
          class="w-full px-3 py-2 border rounded-md bg-background"
        />
        <div class="flex items-center gap-2">
          <input
            bind:this={bannerInputRef}
            type="file"
            accept="image/*"
            onchange={(e) => handleFileSelect(e, 'banner')}
            class="hidden"
          />
          <button
            type="button"
            onclick={() => bannerInputRef?.click()}
            class="px-3 py-1.5 text-sm border rounded-md hover:bg-accent"
          >
            Upload Image
          </button>
          {#if formData.banner}
            <div class="h-10 w-24 rounded overflow-hidden">
              <img
                src={formData.banner}
                alt="Banner preview"
                class="h-full w-full object-cover"
              />
            </div>
          {/if}
        </div>
        <p class="text-sm text-muted-foreground">
          URL to a wide banner image for your profile. You can upload an image or provide a URL.
        </p>
      </div>
    </div>

    <!-- Website and NIP-05 -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <!-- Website -->
      <div class="space-y-2">
        <label for="website" class="block text-sm font-medium">
          Website
        </label>
        <input
          id="website"
          type="text"
          bind:value={formData.website}
          placeholder="https://yourwebsite.com"
          class="w-full px-3 py-2 border rounded-md bg-background"
        />
        <p class="text-sm text-muted-foreground">
          Your personal website or social media link.
        </p>
      </div>

      <!-- NIP-05 -->
      <div class="space-y-2">
        <label for="nip05" class="block text-sm font-medium">
          NIP-05 Identifier
        </label>
        <input
          id="nip05"
          type="text"
          bind:value={formData.nip05}
          placeholder="you@example.com"
          class="w-full px-3 py-2 border rounded-md bg-background"
        />
        <p class="text-sm text-muted-foreground">
          Your verified Nostr identifier.
        </p>
      </div>
    </div>

    <!-- Bot Account -->
    <div class="flex items-center justify-between rounded-lg border p-4">
      <div class="space-y-0.5">
        <label for="bot" class="text-base font-medium">
          Bot Account
        </label>
        <p class="text-sm text-muted-foreground">
          Mark this account as automated or a bot.
        </p>
      </div>
      <input
        id="bot"
        type="checkbox"
        bind:checked={formData.bot}
        class="h-5 w-5"
      />
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      disabled={isPending || isUploading}
      class="w-full md:w-auto px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {#if isPending || isUploading}
        <span class="inline-block animate-spin mr-2">⏳</span>
      {/if}
      Save Profile
    </button>
  </form>
</div>

<style>
  /* Additional styles can go here if needed */
</style>

// src/components/EditProfileForm.tsx
import React, { useEffect, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useCurrentUser } from '@/hooks/useCurrentUser';
import { useNostrPublish } from '@/hooks/useNostrPublish';
import { useToast } from '@/hooks/useToast';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Loader2, Upload } from 'lucide-react';
import { NSchema as n, type NostrMetadata } from '@nostrify/nostrify';
import { useQueryClient } from '@tanstack/react-query';
import { useUploadFile } from '@/hooks/useUploadFile';

/**
 * Form component for editing Nostr user profile metadata (kind 0 event).
 * Supports text fields, image uploads, and NIP-05 verification.
 */
export const EditProfileForm: React.FC = () => {
  const queryClient = useQueryClient();

  const { user, metadata } = useCurrentUser();
  const { mutateAsync: publishEvent, isPending } = useNostrPublish();
  const { mutateAsync: uploadFile, isPending: isUploading } = useUploadFile();
  const { toast } = useToast();

  // Initialize the form with default values
  const form = useForm<NostrMetadata>({
    resolver: zodResolver(n.metadata()),
    defaultValues: {
      name: '',
      about: '',
      picture: '',
      banner: '',
      website: '',
      nip05: '',
      bot: false,
    },
  });

  // Update form values when user data is loaded
  useEffect(() => {
    if (metadata) {
      form.reset({
        name: metadata.name || '',
        about: metadata.about || '',
        picture: metadata.picture || '',
        banner: metadata.banner || '',
        website: metadata.website || '',
        nip05: metadata.nip05 || '',
        bot: metadata.bot || false,
      });
    }
  }, [metadata, form]);

  // Handle file uploads for profile picture and banner
  const uploadPicture = async (file: File, field: 'picture' | 'banner') => {
    try {
      // The first tuple in the array contains the URL
      const [[_, url]] = await uploadFile(file);
      form.setValue(field, url);
      toast({
        title: 'Success',
        description: `${field === 'picture' ? 'Profile picture' : 'Banner'} uploaded successfully`,
      });
    } catch (error) {
      console.error(`Failed to upload ${field}:`, error);
      toast({
        title: 'Error',
        description: `Failed to upload ${field === 'picture' ? 'profile picture' : 'banner'}. Please try again.`,
        variant: 'destructive',
      });
    }
  };

  const onSubmit = async (values: NostrMetadata) => {
    if (!user) {
      toast({
        title: 'Error',
        description: 'You must be logged in to update your profile',
        variant: 'destructive',
      });
      return;
    }

    try {
      // Combine existing metadata with new values
      const data = { ...metadata, ...values };

      // Clean up empty values
      for (const key in data) {
        if (data[key] === '') {
          delete data[key];
        }
      }

      // Publish the metadata event (kind 0)
      await publishEvent({
        kind: 0,
        content: JSON.stringify(data),
      });

      // Invalidate queries to refresh the data
      queryClient.invalidateQueries({ queryKey: ['logins'] });
      queryClient.invalidateQueries({ queryKey: ['author', user.pubkey] });

      toast({
        title: 'Success',
        description: 'Your profile has been updated',
      });
    } catch (error) {
      console.error('Failed to update profile:', error);
      toast({
        title: 'Error',
        description: 'Failed to update your profile. Please try again.',
        variant: 'destructive',
      });
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Name</FormLabel>
              <FormControl>
                <Input placeholder="Your name" {...field} />
              </FormControl>
              <FormDescription>
                This is your display name that will be displayed to others.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="about"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Bio</FormLabel>
              <FormControl>
                <Textarea 
                  placeholder="Tell others about yourself" 
                  className="resize-none" 
                  {...field} 
                />
              </FormControl>
              <FormDescription>
                A short description about yourself.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <FormField
            control={form.control}
            name="picture"
            render={({ field }) => (
              <ImageUploadField
                field={field}
                label="Profile Picture"
                placeholder="https://example.com/profile.jpg"
                description="URL to your profile picture. You can upload an image or provide a URL."
                previewType="square"
                onUpload={(file) => uploadPicture(file, 'picture')}
              />
            )}
          />

          <FormField
            control={form.control}
            name="banner"
            render={({ field }) => (
              <ImageUploadField
                field={field}
                label="Banner Image"
                placeholder="https://example.com/banner.jpg"
                description="URL to a wide banner image for your profile. You can upload an image or provide a URL."
                previewType="wide"
                onUpload={(file) => uploadPicture(file, 'banner')}
              />
            )}
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <FormField
            control={form.control}
            name="website"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Website</FormLabel>
                <FormControl>
                  <Input placeholder="https://yourwebsite.com" {...field} />
                </FormControl>
                <FormDescription>
                  Your personal website or social media link.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="nip05"
            render={({ field }) => (
              <FormItem>
                <FormLabel>NIP-05 Identifier</FormLabel>
                <FormControl>
                  <Input placeholder="you@example.com" {...field} />
                </FormControl>
                <FormDescription>
                  Your verified Nostr identifier.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <FormField
          control={form.control}
          name="bot"
          render={({ field }) => (
            <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4">
              <div className="space-y-0.5">
                <FormLabel className="text-base">Bot Account</FormLabel>
                <FormDescription>
                  Mark this account as automated or a bot.
                </FormDescription>
              </div>
              <FormControl>
                <Switch
                  checked={field.value}
                  onCheckedChange={field.onChange}
                />
              </FormControl>
            </FormItem>
          )}
        />

        <Button 
          type="submit" 
          className="w-full md:w-auto" 
          disabled={isPending || isUploading}
        >
          {(isPending || isUploading) && (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          )}
          Save Profile
        </Button>
      </form>
    </Form>
  );
};

// Reusable component for image upload fields
interface ImageUploadFieldProps {
  field: {
    value: string | undefined;
    onChange: (value: string) => void;
    name: string;
    onBlur: () => void;
  };
  label: string;
  placeholder: string;
  description: string;
  previewType: 'square' | 'wide';
  onUpload: (file: File) => void;
}

const ImageUploadField: React.FC<ImageUploadFieldProps> = ({
  field,
  label,
  placeholder,
  description,
  previewType,
  onUpload,
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);

  return (
    <FormItem>
      <FormLabel>{label}</FormLabel>
      <div className="flex flex-col gap-2">
        <FormControl>
          <Input
            placeholder={placeholder}
            name={field.name}
            value={field.value ?? ''}
            onChange={e => field.onChange(e.target.value)}
            onBlur={field.onBlur}
          />
        </FormControl>
        <div className="flex items-center gap-2">
          <input 
            type="file" 
            ref={fileInputRef}
            accept="image/*"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                onUpload(file);
              }
            }}
          />
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => fileInputRef.current?.click()}
          >
            <Upload className="h-4 w-4 mr-2" />
            Upload Image
          </Button>
          {field.value && (
            <div className={`h-10 ${previewType === 'square' ? 'w-10' : 'w-24'} rounded overflow-hidden`}>
              <img 
                src={field.value} 
                alt={`${label} preview`} 
                className="h-full w-full object-cover"
              />
            </div>
          )}
        </div>
      </div>
      <FormDescription>
        {description}
      </FormDescription>
      <FormMessage />
    </FormItem>
  );
};
