// src/components/comments/CommentsSection.tsx
import { useComments } from '@/hooks/useComments';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { MessageSquare } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { NostrEvent } from '@nostrify/nostrify';
import { CommentForm } from './CommentForm';
import { Comment } from './Comment';

interface CommentsSectionProps {
  root: NostrEvent | URL;
  title?: string;
  emptyStateMessage?: string;
  emptyStateSubtitle?: string;
  className?: string;
  limit?: number;
}

/**
 * Comments section component displaying threaded comments with compose form.
 * Shows loading state, empty state, and error handling for comment threads.
 * @param props - Section configuration including root event, title, and display options
 */
export function CommentsSection({
  root,
  title = "Comments",
  emptyStateMessage = "No comments yet",
  emptyStateSubtitle = "Be the first to share your thoughts!",
  className,
  limit = 500,
}: CommentsSectionProps) {
  const { data: commentsData, isLoading, error } = useComments(root, limit);
  const comments = commentsData?.topLevelComments || [];

  if (error) {
    return (
      <Card className="rounded-none sm:rounded-lg mx-0 sm:mx-0">
        <CardContent className="px-2 py-6 sm:p-6">
          <div className="text-center text-muted-foreground">
            <MessageSquare className="h-8 w-8 mx-auto mb-2 opacity-50" />
            <p>Failed to load comments</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={cn("rounded-none sm:rounded-lg mx-0 sm:mx-0", className)}>
      <CardHeader className="px-2 pt-6 pb-4 sm:p-6">
        <CardTitle className="flex items-center space-x-2">
          <MessageSquare className="h-5 w-5" />
          <span>{title}</span>
          {!isLoading && (
            <span className="text-sm font-normal text-muted-foreground">
              ({comments.length})
            </span>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="px-2 pb-6 pt-4 sm:p-6 sm:pt-0 space-y-6">
        {/* Comment Form */}
        <CommentForm root={root} />

        {/* Comments List */}
        {isLoading ? (
          <div className="space-y-4">
            {[...Array(3)].map((_, i) => (
              <Card key={i} className="bg-card/50">
                <CardContent className="p-4">
                  <div className="space-y-3">
                    <div className="flex items-center space-x-3">
                      <Skeleton className="h-8 w-8 rounded-full" />
                      <div className="space-y-1">
                        <Skeleton className="h-4 w-24" />
                        <Skeleton className="h-3 w-16" />
                      </div>
                    </div>
                    <Skeleton className="h-16 w-full" />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : comments.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <MessageSquare className="h-12 w-12 mx-auto mb-4 opacity-30" />
            <p className="text-lg font-medium mb-2">{emptyStateMessage}</p>
            <p className="text-sm">{emptyStateSubtitle}</p>
          </div>
        ) : (
          <div className="space-y-4">
            {comments.map((comment) => (
              <Comment
                key={comment.id}
                root={root}
                comment={comment}
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// src/lib/components/comments/CommentsSection.svelte
<script lang="ts">
  import { cn } from '$lib/utils';
  import type { TrustedEvent } from '@welshman/util';
  import CommentForm from './CommentForm.svelte';
  import Comment from './Comment.svelte';

  interface Props {
    root: TrustedEvent | URL;
    title?: string;
    emptyStateMessage?: string;
    emptyStateSubtitle?: string;
    class?: string;
    limit?: number;
  }

  let {
    root,
    title = 'Comments',
    emptyStateMessage = 'No comments yet',
    emptyStateSubtitle = 'Be the first to share your thoughts!',
    class: className,
    limit = 500
  }: Props = $props();

  // TODO: Integrate with Welshman comments data
  // import { createQuery } from '@tanstack/svelte-query';
  // const commentsQuery = createQuery({
  //   queryKey: ['comments', getRootId(root), limit],
  //   queryFn: () => fetchComments(root, limit),
  // });
  // const commentsData = $derived(commentsQuery.data);
  // const isLoading = $derived(commentsQuery.isLoading);
  // const error = $derived(commentsQuery.error);

  const commentsData = $state<any>(null);
  const isLoading = $state(false);
  const error = $state<Error | null>(null);

  const comments = $derived(commentsData?.topLevelComments || []);
</script>

<div class={cn('rounded-none sm:rounded-lg mx-0 sm:mx-0 border bg-card text-card-foreground shadow-sm', className)}>
  <!-- Header -->
  <div class="px-2 pt-6 pb-4 sm:p-6">
    <h3 class="text-2xl font-semibold leading-none tracking-tight flex items-center space-x-2">
      <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
      </svg>
      <span>{title}</span>
      {#if !isLoading}
        <span class="text-sm font-normal text-muted-foreground">
          ({comments.length})
        </span>
      {/if}
    </h3>
  </div>

  <!-- Content -->
  <div class="px-2 pb-6 pt-4 sm:p-6 sm:pt-0 space-y-6">
    <!-- Comment Form -->
    <CommentForm {root} />

    <!-- Error State -->
    {#if error}
      <div class="text-center text-muted-foreground py-8">
        <svg class="h-8 w-8 mx-auto mb-2 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
        </svg>
        <p>Failed to load comments</p>
      </div>
    <!-- Loading State -->
    {:else if isLoading}
      <div class="space-y-4">
        {#each Array(3) as _, i}
          <div class="rounded-lg border bg-card/50 text-card-foreground shadow-sm">
            <div class="p-4">
              <div class="space-y-3">
                <div class="flex items-center space-x-3">
                  <div class="h-8 w-8 rounded-full bg-muted animate-pulse"></div>
                  <div class="space-y-1">
                    <div class="h-4 w-24 bg-muted rounded animate-pulse"></div>
                    <div class="h-3 w-16 bg-muted rounded animate-pulse"></div>
                  </div>
                </div>
                <div class="h-16 w-full bg-muted rounded animate-pulse"></div>
              </div>
            </div>
          </div>
        {/each}
      </div>
    <!-- Empty State -->
    {:else if comments.length === 0}
      <div class="text-center py-8 text-muted-foreground">
        <svg class="h-12 w-12 mx-auto mb-4 opacity-30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
        </svg>
        <p class="text-lg font-medium mb-2">{emptyStateMessage}</p>
        <p class="text-sm">{emptyStateSubtitle}</p>
      </div>
    <!-- Comments List -->
    {:else}
      <div class="space-y-4">
        {#each comments as comment (comment.id)}
          <Comment {root} {comment} {limit} />
        {/each}
      </div>
    {/if}
  </div>
</div>
