// src/components/ZapButton.tsx
import { ZapDialog } from '@/components/ZapDialog';
import { useZaps } from '@/hooks/useZaps';
import { useWallet } from '@/hooks/useWallet';
import { useCurrentUser } from '@/hooks/useCurrentUser';
import { useAuthor } from '@/hooks/useAuthor';
import { Zap } from 'lucide-react';
import type { Event } from 'nostr-tools';

interface ZapButtonProps {
  target: Event;
  className?: string;
  showCount?: boolean;
  zapData?: { count: number; totalSats: number; isLoading?: boolean };
}

/**
 * Button component for sending Lightning zaps to a Nostr event.
 * Opens ZapDialog when clicked and displays total sats zapped.
 *
 * @param props - Component properties
 * @param props.target - The Nostr event to zap
 * @param props.className - Optional CSS class names
 * @param props.showCount - Whether to display zap count (default: true)
 * @param props.zapData - Optional external zap data to avoid refetching
 */
export function ZapButton({
  target,
  className = "text-xs ml-1",
  showCount = true,
  zapData: externalZapData
}: ZapButtonProps) {
  const { user } = useCurrentUser();
  const { data: author } = useAuthor(target?.pubkey || '');
  const { webln, activeNWC } = useWallet();

  // Only fetch data if not provided externally
  const { totalSats: fetchedTotalSats, isLoading } = useZaps(
    externalZapData ? [] : target ?? [], // Empty array prevents fetching if external data provided
    webln,
    activeNWC
  );

  // Don't show zap button if user is not logged in, is the author, or author has no lightning address
  if (!user || !target || user.pubkey === target.pubkey || (!author?.metadata?.lud16 && !author?.metadata?.lud06)) {
    return null;
  }

  // Use external data if provided, otherwise use fetched data
  const totalSats = externalZapData?.totalSats ?? fetchedTotalSats;
  const showLoading = externalZapData?.isLoading || isLoading;

  return (
    <ZapDialog target={target}>
      <div className={`flex items-center gap-1 ${className}`}>
        <Zap className="h-4 w-4" />
        <span className="text-xs">
          {showLoading ? (
            '...'
          ) : showCount && totalSats > 0 ? (
            `${totalSats.toLocaleString()}`
          ) : (
            'Zap'
          )}
        </span>
      </div>
    </ZapDialog>
  );
}

// src/lib/components/ZapButton.svelte
<script lang="ts">
  import ZapDialog from './ZapDialog.svelte';

  interface Props {
    target: any; // Nostr event
    class?: string;
    showCount?: boolean;
    zapData?: { count: number; totalSats: number; isLoading?: boolean };
  }

  let {
    target,
    class: className = "text-xs ml-1",
    showCount = true,
    zapData: externalZapData
  }: Props = $props();

  // TODO: Integrate with current user hook
  // import { currentUser } from '$lib/stores/auth';
  // const user = $derived($currentUser);
  const user = $state<any>(null);

  // TODO: Integrate with author hook to fetch author metadata
  // import { createQuery } from '@tanstack/svelte-query';
  // const authorQuery = createQuery({...});
  // const author = $derived($authorQuery.data);
  const author = $state<any>(null);

  // TODO: Integrate with wallet hook
  // import { webln, activeNWC } from '$lib/stores/wallet';
  const webln = $state<any>(null);
  const activeNWC = $state<any>(null);

  // TODO: Integrate with zaps hook to fetch zap stats
  // import { useZaps } from '$lib/hooks/useZaps';
  // const { totalSats, isLoading } = useZaps(target, webln, activeNWC);
  const fetchedTotalSats = $state(0);
  const isLoading = $state(false);

  // Use external data if provided, otherwise use fetched data
  const totalSats = $derived(externalZapData?.totalSats ?? fetchedTotalSats);
  const showLoading = $derived(externalZapData?.isLoading || isLoading);

  // Don't show zap button if user is not logged in, is the author, or author has no lightning address
  const shouldShow = $derived(
    user &&
    target &&
    user.pubkey !== target.pubkey &&
    (author?.metadata?.lud16 || author?.metadata?.lud06)
  );
</script>

{#if shouldShow}
  <ZapDialog {target}>
    <div class="flex items-center gap-1 {className}">
      <!-- Zap Icon -->
      <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M13 10V3L4 14h7v7l9-11h-7z"
        />
      </svg>
      <span class="text-xs">
        {#if showLoading}
          ...
        {:else if showCount && totalSats > 0}
          {totalSats.toLocaleString()}
        {:else}
          Zap
        {/if}
      </span>
    </div>
  </ZapDialog>
{/if}
