// src/components/ZapDialog.tsx
import { useState, useEffect, useRef, forwardRef } from 'react';
import { Zap, Copy, Check, ExternalLink, Sparkle, Sparkles, Star, Rocket, ArrowLeft, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
  DrawerClose,
} from '@/components/ui/drawer';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { useCurrentUser } from '@/hooks/useCurrentUser';
import { useAuthor } from '@/hooks/useAuthor';
import { useToast } from '@/hooks/useToast';
import { useZaps } from '@/hooks/useZaps';
import { useWallet } from '@/hooks/useWallet';
import { useIsMobile } from '@/hooks/useIsMobile';
import type { Event } from 'nostr-tools';
import QRCode from 'qrcode';
import type { WebLNProvider } from "@webbtc/webln-types";

interface ZapDialogProps {
  target: Event;
  children?: React.ReactNode;
  className?: string;
}

const presetAmounts = [
  { amount: 1, icon: Sparkle },
  { amount: 50, icon: Sparkles },
  { amount: 100, icon: Zap },
  { amount: 250, icon: Star },
  { amount: 1000, icon: Rocket },
];

interface ZapContentProps {
  invoice: string | null;
  amount: number | string;
  comment: string;
  isZapping: boolean;
  qrCodeUrl: string;
  copied: boolean;
  webln: WebLNProvider | null;
  handleZap: () => void;
  handleCopy: () => void;
  openInWallet: () => void;
  setAmount: (amount: number | string) => void;
  setComment: (comment: string) => void;
  inputRef: React.RefObject<HTMLInputElement>;
  zap: (amount: number, comment: string) => void;
}

// Moved ZapContent outside of ZapDialog to prevent re-renders causing focus loss
const ZapContent = forwardRef<HTMLDivElement, ZapContentProps>(({
  invoice,
  amount,
  comment,
  isZapping,
  qrCodeUrl,
  copied,
  webln,
  handleZap,
  handleCopy,
  openInWallet,
  setAmount,
  setComment,
  inputRef,
  zap,
}, ref) => (
  <div ref={ref}>
    {invoice ? (
      <div className="flex flex-col h-full min-h-0">
        {/* Payment amount display */}
        <div className="text-center pt-4">
          <div className="text-2xl font-bold">{amount} sats</div>
        </div>

        <Separator className="my-4" />

        <div className="flex flex-col justify-center min-h-0 flex-1 px-2">
          {/* QR Code */}
          <div className="flex justify-center">
            <Card className="p-3 [@media(max-height:680px)]:max-w-[65vw] max-w-[95vw] mx-auto">
              <CardContent className="p-0 flex justify-center">
                {qrCodeUrl ? (
                  <img
                    src={qrCodeUrl}
                    alt="Lightning Invoice QR Code"
                    className="w-full h-auto aspect-square max-w-full object-contain"
                  />
                ) : (
                  <div className="w-full aspect-square bg-muted animate-pulse rounded" />
                )}
              </CardContent>
            </Card>
          </div>

          {/* Invoice input */}
          <div className="space-y-2 mt-4">
            <Label htmlFor="invoice">Lightning Invoice</Label>
            <div className="flex gap-2 min-w-0">
              <Input
                id="invoice"
                value={invoice}
                readOnly
                className="font-mono text-xs min-w-0 flex-1 overflow-hidden text-ellipsis"
                onClick={(e) => e.currentTarget.select()}
              />
              <Button
                variant="outline"
                size="icon"
                onClick={handleCopy}
                className="shrink-0"
              >
                {copied ? (
                  <Check className="h-4 w-4 text-green-600" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </div>
          </div>

          {/* Payment buttons */}
          <div className="space-y-3 mt-4">
            {webln && (
              <Button
                onClick={() => {
                  const finalAmount = typeof amount === 'string' ? parseInt(amount, 10) : amount;
                  zap(finalAmount, comment);
                }}
                disabled={isZapping}
                className="w-full"
                size="lg"
              >
                <Zap className="h-4 w-4 mr-2" />
                {isZapping ? "Processing..." : "Pay with WebLN"}
              </Button>
            )}

            <Button
              variant="outline"
              onClick={openInWallet}
              className="w-full"
              size="lg"
            >
              <ExternalLink className="h-4 w-4 mr-2" />
              Open in Lightning Wallet
            </Button>

            <div className="text-xs sm:text-[.65rem] text-muted-foreground text-center">
              Scan the QR code or copy the invoice to pay with any Lightning wallet.
            </div>
          </div>
        </div>
      </div>
    ) : (
      <>
        <div className="grid gap-3 px-4 py-4 w-full overflow-hidden">
          <ToggleGroup
            type="single"
            value={String(amount)}
            onValueChange={(value) => {
              if (value) {
                setAmount(parseInt(value, 10));
              }
            }}
            className="grid grid-cols-5 gap-1 w-full"
          >
            {presetAmounts.map(({ amount: presetAmount, icon: Icon }) => (
              <ToggleGroupItem
                key={presetAmount}
                value={String(presetAmount)}
                className="flex flex-col h-auto min-w-0 text-xs px-1 py-2"
              >
                <Icon className="h-4 w-4 mb-1" />
                <span className="truncate">{presetAmount}</span>
              </ToggleGroupItem>
            ))}
          </ToggleGroup>
          <div className="flex items-center gap-2">
            <div className="h-px flex-1 bg-muted" />
            <span className="text-xs text-muted-foreground">OR</span>
            <div className="h-px flex-1 bg-muted" />
          </div>
          <Input
            ref={inputRef}
            id="custom-amount"
            type="number"
            placeholder="Custom amount"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className="w-full text-sm"
          />
          <Textarea
            id="custom-comment"
            placeholder="Add a comment (optional)"
            value={comment}
            onChange={(e) => setComment(e.target.value)}
            className="w-full resize-none text-sm"
            rows={2}
          />
        </div>
        <div className="px-4 pb-4">
          <Button onClick={handleZap} className="w-full" disabled={isZapping} size="default">
            {isZapping ? (
              'Creating invoice...'
            ) : (
              <>
                <Zap className="h-4 w-4 mr-2" />
                Zap {amount} sats
              </>
            )}
          </Button>
        </div>
      </>
    )}
  </div>
));
ZapContent.displayName = 'ZapContent';

/**
 * Dialog component for sending Lightning Network zaps to a Nostr event.
 * Supports WebLN and NWC wallets, displays QR codes, and handles invoice generation.
 *
 * @param props - Component properties
 * @param props.target - The Nostr event to zap
 * @param props.children - Optional custom trigger element
 * @param props.className - Optional CSS class names
 */
export function ZapDialog({ target, children, className }: ZapDialogProps) {
  const [open, setOpen] = useState(false);
  const { user } = useCurrentUser();
  const { data: author } = useAuthor(target.pubkey);
  const { toast } = useToast();
  const { webln, activeNWC } = useWallet();
  const { zap, isZapping, invoice, setInvoice } = useZaps(target, webln, activeNWC, () => setOpen(false));
  const [amount, setAmount] = useState<number | string>(100);
  const [comment, setComment] = useState<string>('');
  const [copied, setCopied] = useState(false);
  const [qrCodeUrl, setQrCodeUrl] = useState<string>('');
  const inputRef = useRef<HTMLInputElement>(null);
  const isMobile = useIsMobile();

  useEffect(() => {
    if (target) {
      setComment('Zapped via nostr.blue!');
    }
  }, [target]);

  // Generate QR code
  useEffect(() => {
    let isCancelled = false;

    const generateQR = async () => {
      if (!invoice) {
        setQrCodeUrl('');
        return;
      }

      try {
        const url = await QRCode.toDataURL(invoice.toUpperCase(), {
          width: 512,
          margin: 2,
          color: {
            dark: '#000000',
            light: '#FFFFFF',
          },
        });

        if (!isCancelled) {
          setQrCodeUrl(url);
        }
      } catch (err) {
        if (!isCancelled) {
          console.error('Failed to generate QR code:', err);
        }
      }
    };

    generateQR();

    return () => {
      isCancelled = true;
    };
  }, [invoice]);

  const handleCopy = async () => {
    if (invoice) {
      await navigator.clipboard.writeText(invoice);
      setCopied(true);
      toast({
        title: 'Invoice copied',
        description: 'Lightning invoice copied to clipboard',
      });
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const openInWallet = () => {
    if (invoice) {
      const lightningUrl = `lightning:${invoice}`;
      window.open(lightningUrl, '_blank', 'noopener,noreferrer');
    }
  };

  useEffect(() => {
    if (open) {
      setAmount(100);
      setInvoice(null);
      setCopied(false);
      setQrCodeUrl('');
    } else {
      // Clean up state when dialog closes
      setAmount(100);
      setInvoice(null);
      setCopied(false);
      setQrCodeUrl('');
    }
  }, [open, setInvoice]);

  const handleZap = () => {
    const finalAmount = typeof amount === 'string' ? parseInt(amount, 10) : amount;
    zap(finalAmount, comment);
  };

  const contentProps = {
    invoice,
    amount,
    comment,
    isZapping,
    qrCodeUrl,
    copied,
    webln,
    handleZap,
    handleCopy,
    openInWallet,
    setAmount,
    setComment,
    inputRef,
    zap,
  };

  if (!user || user.pubkey === target.pubkey || !author?.metadata?.lud06 && !author?.metadata?.lud16) {
    return null;
  }

  if (isMobile) {
    // Use drawer for entire mobile flow, make it full-screen when showing invoice
    return (
      <Drawer
        open={open}
        onOpenChange={(newOpen) => {
          // Reset invoice when closing
          if (!newOpen) {
            setInvoice(null);
            setQrCodeUrl('');
          }
          setOpen(newOpen);
        }}
        dismissible={true} // Always allow dismissal via drag
        snapPoints={invoice ? [0.5, 0.75, 0.98] : [0.98]}
        activeSnapPoint={invoice ? 0.98 : 0.98}
        modal={true}
        shouldScaleBackground={false}
        fadeFromIndex={0}
      >
        <DrawerTrigger asChild>
          <div className={`cursor-pointer ${className || ''}`}>
            {children}
          </div>
        </DrawerTrigger>
        <DrawerContent
          key={invoice ? 'payment' : 'form'}
          className={cn(
            "transition-all duration-300",
            invoice ? "h-full max-h-screen" : "max-h-[98vh]"
          )}
          data-testid="zap-modal"
        >
          <DrawerHeader className="text-center relative">
            {/* Back button when showing invoice */}
            {invoice && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setInvoice(null);
                  setQrCodeUrl('');
                }}
                className="absolute left-4 top-4 flex items-center gap-2"
              >
                <ArrowLeft className="h-4 w-4" />
              </Button>
            )}

            {/* Close button */}
            <DrawerClose asChild>
              <Button
                variant="ghost"
                size="sm"
                className="absolute right-4 top-4"
              >
                <X className="h-4 w-4" />
                <span className="sr-only">Close</span>
              </Button>
            </DrawerClose>

            <DrawerTitle className="text-lg break-words pt-2">
              {invoice ? 'Lightning Payment' : 'Send a Zap'}
            </DrawerTitle>
            <DrawerDescription className="text-sm break-words text-center">
              {invoice ? (
                'Pay with Bitcoin Lightning Network'
              ) : (
                'Zaps are small Bitcoin payments that support the creator of this item. If you enjoyed this, consider sending a zap!'
              )}
            </DrawerDescription>
          </DrawerHeader>
          <div className="flex-1 overflow-y-auto px-4 pb-4">
            <ZapContent {...contentProps} />
          </div>
        </DrawerContent>
      </Drawer>
    );
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <div className={`cursor-pointer ${className || ''}`}>
          {children}
        </div>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px] max-h-[95vh] overflow-hidden" data-testid="zap-modal">
        <DialogHeader>
          <DialogTitle className="text-lg break-words">
            {invoice ? 'Lightning Payment' : 'Send a Zap'}
          </DialogTitle>
          <DialogDescription className="text-sm text-center break-words">
            {invoice ? (
              'Pay with Bitcoin Lightning Network'
            ) : (
              <>
                Zaps are small Bitcoin payments that support the creator of this item. If you enjoyed this, consider sending a zap!
              </>
            )}
          </DialogDescription>
        </DialogHeader>
        <div className="overflow-y-auto">
          <ZapContent {...contentProps} />
        </div>
      </DialogContent>
    </Dialog>
  );
}

// src/lib/components/ZapDialog.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { currentUser } from '$lib/stores/auth';
  import { fetchAuthor, type AuthorData } from '$lib/stores/author.svelte';
  import { useZaps } from '$lib/stores/zaps.svelte';
  import { getWalletStatus } from '$lib/stores/wallet.svelte';
  import type { TrustedEvent } from '@welshman/util';
  import QRCode from 'qrcode';

  interface Props {
    target: TrustedEvent;
    children?: import('svelte').Snippet;
    class?: string;
  }

  let { target, children, class: className }: Props = $props();

  let isOpen = $state(false);
  let amount = $state<number | string>(100);
  let comment = $state('Zapped with nostr.blue!');
  let copied = $state(false);
  let qrCodeUrl = $state('');

  // Query author metadata for lightning address
  const authorQuery = createQuery<AuthorData>(() => ({
    queryKey: ['author', target.pubkey],
    queryFn: ({ signal }) => fetchAuthor(target.pubkey, signal),
    enabled: !!target?.pubkey,
    staleTime: 5 * 60 * 1000 // 5 minutes
  }));

  const author = $derived(authorQuery.data as AuthorData | undefined);

  // Get wallet status
  const walletStatus = getWalletStatus();

  // Use zaps hook to fetch and manage zaps
  const zaps = useZaps(
    target as import('nostr-tools').Event,
    walletStatus.webln,
    walletStatus.activeNWC,
    () => {
      // On zap success, close dialog
      isOpen = false;
    }
  );

  // Mobile detection (simple check)
  const isMobile = $state(
    typeof window !== 'undefined' && window.innerWidth < 768
  );

  // Preset zap amounts with icons
  const presetAmounts = [
    { amount: 1, label: '✨' },
    { amount: 50, label: '⭐' },
    { amount: 100, label: '⚡' },
    { amount: 250, label: '🌟' },
    { amount: 1000, label: '🚀' },
  ];

  // Get invoice from zaps hook
  const invoice = $derived(zaps.invoice);
  const isZapping = $derived(zaps.isZapping);

  // Reset state when dialog opens/closes
  $effect(() => {
    if (isOpen) {
      amount = 100;
      zaps.resetInvoice();
      copied = false;
      qrCodeUrl = '';
      comment = 'Zapped with nostr.blue!';
    }
  });

  // Generate QR code when invoice changes
  $effect(() => {
    if (invoice) {
      QRCode.toDataURL(invoice.toUpperCase(), {
        width: 256,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#FFFFFF'
        }
      })
        .then(url => {
          qrCodeUrl = url;
        })
        .catch(error => {
          console.error('Failed to generate QR code:', error);
          qrCodeUrl = '';
        });
    } else {
      qrCodeUrl = '';
    }
  });

  async function handleZap() {
    const finalAmount = typeof amount === 'string' ? parseInt(amount, 10) : amount;

    if (!finalAmount || finalAmount <= 0) {
      alert('Please enter a valid amount');
      return;
    }

    // Call the zap function from useZaps hook
    await zaps.zap(finalAmount, comment);
  }

  async function handleCopy() {
    if (invoice && typeof navigator !== 'undefined') {
      await navigator.clipboard.writeText(invoice);
      copied = true;
      setTimeout(() => (copied = false), 2000);
    }
  }

  function openInWallet() {
    if (invoice) {
      const lightningUrl = `lightning:${invoice}`;
      window.open(lightningUrl, '_blank');
    }
  }

  // Don't render if conditions aren't met
  const shouldShow = $derived(
    $currentUser &&
    target &&
    $currentUser.pubkey !== target.pubkey &&
    (author?.metadata?.lud06 || author?.metadata?.lud16)
  );
</script>

{#if shouldShow}

  <!-- Desktop Dialog -->
  {#if !isMobile && isOpen}
    <div
      class="fixed inset-0 z-50 bg-black/50"
      onclick={() => (isOpen = false)}
      role="presentation"
    >
      <div
        class="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-[425px] max-h-[95vh] overflow-hidden bg-background rounded-lg shadow-lg"
        onclick={(e) => e.stopPropagation()}
        onkeydown={(e) => e.stopPropagation()}
        role="dialog"
        tabindex="-1"
      >
        <div class="p-6">
          <h2 class="text-lg font-semibold mb-2">
            {invoice ? 'Lightning Payment' : 'Send a Zap'}
          </h2>
          <p class="text-sm text-muted-foreground mb-4">
            {#if invoice}
              Pay with Bitcoin Lightning Network
            {:else}
              Zaps are small Bitcoin payments that support the creator of this item.
            {/if}
          </p>

          {#if invoice}
            <!-- Invoice View -->
            <div class="space-y-4">
              <div class="text-center">
                <div class="text-2xl font-bold">{amount} sats</div>
              </div>

              <div class="h-px bg-border"></div>

              <!-- QR Code Placeholder -->
              <div class="flex justify-center">
                <div class="w-64 h-64 bg-muted rounded-lg flex items-center justify-center">
                  {#if qrCodeUrl && qrCodeUrl !== 'data:image/png;base64,placeholder'}
                    <img src={qrCodeUrl} alt="Lightning Invoice QR Code" class="w-full h-full object-contain" />
                  {:else}
                    <div class="text-muted-foreground text-sm">QR Code</div>
                  {/if}
                </div>
              </div>

              <!-- Invoice Input -->
              <div class="space-y-2">
                <label for="invoice-input" class="block text-sm font-medium">
                  Lightning Invoice
                </label>
                <div class="flex gap-2">
                  <input
                    id="invoice-input"
                    type="text"
                    value={invoice}
                    readonly
                    class="flex-1 px-3 py-2 text-xs font-mono border rounded-md bg-background"
                    onclick={(e) => e.currentTarget.select()}
                  />
                  <button
                    type="button"
                    onclick={handleCopy}
                    class="px-3 py-2 border rounded-md hover:bg-accent"
                  >
                    {#if copied}
                      ✓
                    {:else}
                      📋
                    {/if}
                  </button>
                </div>
              </div>

              <!-- Payment Buttons -->
              <div class="space-y-3">
                {#if walletStatus.webln}
                  <button
                    type="button"
                    onclick={handleZap}
                    disabled={isZapping}
                    class="w-full px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50"
                  >
                    ⚡ {isZapping ? 'Processing...' : 'Pay with WebLN'}
                  </button>
                {/if}

                <button
                  type="button"
                  onclick={openInWallet}
                  class="w-full px-4 py-2 border rounded-md hover:bg-accent"
                >
                  🔗 Open in Lightning Wallet
                </button>

                <p class="text-xs text-muted-foreground text-center">
                  Scan the QR code or copy the invoice to pay with any Lightning wallet.
                </p>
              </div>
            </div>
          {:else}
            <!-- Zap Amount Selection -->
            <div class="space-y-4">
              <!-- Preset Amounts -->
              <div class="grid grid-cols-5 gap-2">
                {#each presetAmounts as preset}
                  <button
                    type="button"
                    onclick={() => (amount = preset.amount)}
                    class="flex flex-col items-center justify-center h-16 px-2 py-2 text-sm border rounded-md hover:bg-accent {amount === preset.amount ? 'ring-2 ring-primary' : ''}"
                  >
                    <span class="text-2xl mb-1">{preset.label}</span>
                    <span class="text-xs">{preset.amount}</span>
                  </button>
                {/each}
              </div>

              <div class="flex items-center gap-2">
                <div class="h-px flex-1 bg-border"></div>
                <span class="text-xs text-muted-foreground">OR</span>
                <div class="h-px flex-1 bg-border"></div>
              </div>

              <!-- Custom Amount -->
              <input
                type="number"
                placeholder="Custom amount"
                bind:value={amount}
                class="w-full px-3 py-2 border rounded-md bg-background"
              />

              <!-- Comment -->
              <textarea
                placeholder="Add a comment (optional)"
                bind:value={comment}
                rows="2"
                class="w-full px-3 py-2 border rounded-md bg-background resize-none"
              ></textarea>

              <!-- Zap Button -->
              <button
                type="button"
                onclick={handleZap}
                disabled={isZapping}
                class="w-full px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {#if isZapping}
                  Creating invoice...
                {:else}
                  ⚡ Zap {amount} sats
                {/if}
              </button>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {/if}

  <!-- Trigger -->
  <button
    type="button"
    onclick={() => (isOpen = true)}
    class="cursor-pointer {className}"
  >
    {#if children}
      {@render children()}
    {:else}
      <span>Zap</span>
    {/if}
  </button>
{/if}
